version: '3'
services:

  #####
  # reverse proxy for the whole environment
  #####

  nginx:
    image: nginx:1.23.1-alpine
    network_mode: host
    volumes:
      - ./dev/resources/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dev/data/:/data

  #####
  # related services from the data-fair stack
  #####

  simple-directory:
    image: ghcr.io/data-fair/simple-directory:5
    ports:
      - 6221:8080
      - 1080:1080
      - 1025:1025
    depends_on:
      - mongo
    environment:
      - DEBUG=session
      - ADMINS=["superadmin@test.com"]
      - PUBLIC_URL=http://localhost:6218/simple-directory
      - MAILDEV_ACTIVE=true
      - STORAGE_TYPE=file
      - ROLES_DEFAULTS=["admin", "contrib", "user"]
      - PROMETHEUS_ACTIVE=false
      - NO_UI=${NO_UI}
    volumes:
      - ./dev/resources/users.json:/webapp/data/users.json
      - ./dev/resources/organizations.json:/webapp/data/organizations.json

  data-fair:
    image: ghcr.io/data-fair/data-fair:master
    ports:
      - 6222:8080
    depends_on:
      mongo:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    restart: on-failure:10
    environment:
      - DEBUG=files
      - MONGO_URL=mongodb://mongo:27017/data-fair
      - ES_HOST=elasticsearch:9200
      - DIRECTORY_URL=http://localhost:6218/simple-directory
      - PRIVATE_DIRECTORY_URL=http://simple-directory:8080
      - PUBLIC_URL=http://localhost:6218/data-fair
      - WS_PUBLIC_URL=ws://localhost:6218/data-fair
      - PROMETHEUS_ACTIVE=false

  #####
  # db and search engine
  #####

  elasticsearch:
    image: ghcr.io/data-fair/elasticsearch:7.17.9
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      timeout: 10s
      interval: 10s
      retries: 10

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017

  #####
  # dev tools installed through docker for convenience
  #####

  jtd:
    build: ./dev/docker/jtd
    profiles:
      - tools
    volumes:
      - ./:/jtd