version: '3'
services:

  #####
  # reverse proxy for the whole environment
  #####

  nginx:
    image: nginx:1.23.1-alpine
    network_mode: host
    volumes:
      - ./dev/resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  #####
  # dev services mapped to local directory
  #####

  api:
    build: ./dev/docker/node
    profiles:
      - dev
    volumes:
      - ./api/:/app/
    command: pnpm dev
    network_mode: host

  ui:
    build: ./dev/docker/node
    profiles:
      - dev
    volumes:
      - ./ui/:/app/
    command: pnpm dev
    network_mode: host
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 6220

  #####
  # related services from the data-fair stack
  #####

  simple-directory:
    image: ghcr.io/data-fair/simple-directory:5
    ports:
      - 6221:8080
      - 1080:1080
      - 1025:1025
    depends_on:
      - mongo
    environment:
      - ADMINS=["superadmin@test.com"]
      - PUBLIC_URL=http://localhost:6218/simple-directory
      - MAILDEV_ACTIVE=true
      - STORAGE_TYPE=file
      - ROLES_DEFAULTS=["admin", "contrib", "user"]
      - PROMETHEUS_ACTIVE=false
    volumes:
      - ./dev/resources/users.json:/webapp/data/users.json
      - ./dev/resources/organizations.json:/webapp/data/organizations.json

  data-fair:
    image: ghcr.io/data-fair/data-fair:3
    ports:
      - 6222:8080
    depends_on:
      - mongo
      - elasticsearch
    restart: on-failure:10
    environment:
      - DEBUG=files
      - MONGO_URL=mongodb://mongo:27017/data-fair
      - ES_HOST=elasticsearch:9200
      - DIRECTORY_URL=http://localhost:6218/simple-directory
      - PRIVATE_DIRECTORY_URL=http://simple-directory:8080
      - PUBLIC_URL=http://localhost:6218/data-fair
      - WS_PUBLIC_URL=ws://localhost:6218/data-fair
      - PROMETHEUS_ACTIVE=false

  #####
  # db and search engine
  #####

  elasticsearch:
    image: ghcr.io/data-fair/elasticsearch:7.17.6
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
