services:

  #####
  # reverse proxy for the whole environment
  #####

  nginx:
    image: nginx:1.23.1-alpine
    network_mode: host
    volumes:
      - ./dev/resources/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dev/data/:/data

  #####
  # related services from the data-fair stack
  #####

  simple-directory:
    image: ghcr.io/data-fair/simple-directory:master
    network_mode: host
    depends_on:
      - mongo
    environment:
      - PUBLIC_URL=http://localhost:5600/simple-directory
      - OBSERVER_ACTIVE=false
      - CIPHER_PASSWORD=dev
      - CONTACT=contact@test.com
      - MONGO_URL=mongodb://localhost:27017/simple-directory
      - PORT=6221
      - DEBUG=session
      - ADMINS=["superadmin@test.com"]
      - STORAGE_TYPE=file
    volumes:
      - ./dev/resources/users.json:/webapp/data/users.json
      - ./dev/resources/organizations.json:/webapp/data/organizations.json

  data-fair:
    image: ghcr.io/data-fair/data-fair:master
    network_mode: host
    depends_on:
      mongo:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    restart: on-failure:10
    environment:
      - PORT=6222
      - DEBUG=files
      - MONGO_URL=mongodb://localhost:27017/data-fair
      - DIRECTORY_URL=http://localhost:5600/simple-directory
      - PUBLIC_URL=http://localhost:5600/data-fair
      - WS_PUBLIC_URL=ws://localhost:5600/data-fair
      - OBSERVER_ACTIVE=false
      - EXTRA_NAV_ITEMS=[{"id":"metrics","can":"admin","iframe":"https://staging-koumoul.com/metrics/embed/home","basePath":"/metrics","icon":"mdi-chart-bar","title":"Audience"}]

  #####
  # db and search engine
  #####

  elasticsearch:
    image: ghcr.io/data-fair/elasticsearch:7.x
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      timeout: 10s
      interval: 2s
      retries: 50

  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  elasticsearch-data: