/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartCategories: typeof import('./../src/components/chart/chart-categories.vue')['default']
    ChartDateHisto: typeof import('./../src/components/chart/chart-date-histo.vue')['default']
    ChartLegend: typeof import('./../src/components/chart/chart-legend.vue')['default']
    ChartSimpleMetric: typeof import('./../src/components/chart/chart-simple-metric.vue')['default']
    DailyApiMetrics: typeof import('./../src/components/daily-api-metrics.vue')['default']
    FilterDatePicker: typeof import('./../src/components/filter/filter-date-picker.vue')['default']
    FilterPeriod: typeof import('./../src/components/filter/filter-period.vue')['default']
    LayoutResizableCard: typeof import('./../src/components/layout/layout-resizable-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
