/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OperationTrack = "readDataFiles" | "readDataAPI" | "openApplication";
export type StatusClass = "info" | "ok" | "redirect" | "clientError" | "serverError";
export type UserClass =
  | "anonymous"
  | "owner"
  | "external"
  | "ownerAPIKey"
  | "externalAPIKey"
  | "ownerProcessing"
  | "externalProcessing";

export interface DailyApiMetric {
  owner?: SessionState;
  day: string;
  resource: Resource;
  operationTrack: OperationTrack;
  statusClass: StatusClass;
  userClass: UserClass;
  refererDomain: string;
  refererApp: string;
  processing?: string;
  nbRequests: number;
  bytes: number;
  duration: number;
}
export interface SessionState {
  user?: User;
  organization?: OrganizationMembership;
  account?: Account;
  accountRole?: string;
  lang?: string;
  dark?: boolean;
  [k: string]: unknown;
}
export interface User {
  email: string;
  id: string;
  name: string;
  organizations: OrganizationMembership[];
  isAdmin?: 0 | 1;
  adminMode?: 0 | 1;
  asAdmin?: UserRef;
  pd?: string;
  ipa?: 0 | 1;
}
export interface OrganizationMembership {
  id: string;
  name: string;
  role: string;
  department?: string;
  departmentName?: string;
  dflt?: boolean;
}
export interface UserRef {
  id: string;
  name: string;
}
export interface Account {
  type: string;
  id: string;
  name: string;
  department?: string;
  departmentName?: string;
}
export interface Resource {
  type: string;
  id: string;
  title?: string;
}

export const dailyApiMetricSchema = {
  "$id": "daily-api-metric/schema.json",
  "type": "object",
  "title": "daily api metric",
  "additionalProperties": false,
  "required": [
    "day",
    "resource",
    "operationTrack",
    "statusClass",
    "userClass",
    "refererDomain",
    "refererApp",
    "nbRequests",
    "bytes",
    "duration"
  ],
  "properties": {
    "owner": {
      "$ref": "@data-fair/lib/types/session-state"
    },
    "day": {
      "type": "string",
      "format": "date"
    },
    "resource": {
      "$ref": "#/definitions/resource"
    },
    "operationTrack": {
      "$ref": "#/definitions/operationTrack"
    },
    "statusClass": {
      "$ref": "#/definitions/statusClass"
    },
    "userClass": {
      "$ref": "#/definitions/userClass"
    },
    "refererDomain": {
      "type": "string"
    },
    "refererApp": {
      "type": "string"
    },
    "processing": {
      "type": "string"
    },
    "nbRequests": {
      "type": "integer",
      "default": 0
    },
    "bytes": {
      "type": "integer",
      "default": 0
    },
    "duration": {
      "type": "number",
      "default": 0
    }
  },
  "definitions": {
    "resource": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "type",
        "id"
      ],
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "operationTrack": {
      "type": "string",
      "enum": [
        "readDataFiles",
        "readDataAPI",
        "openApplication"
      ]
    },
    "statusClass": {
      "type": "string",
      "enum": [
        "info",
        "ok",
        "redirect",
        "clientError",
        "serverError"
      ]
    },
    "userClass": {
      "type": "string",
      "enum": [
        "anonymous",
        "owner",
        "external",
        "ownerAPIKey",
        "externalAPIKey",
        "ownerProcessing",
        "externalProcessing"
      ]
    }
  }
}
