/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AggQuery {
  start: string;
  end: string;
  operationTrack?: "readDataFiles" | "readDataAPI" | "openApplication";
  statusClass?: "info" | "ok" | "redirect" | "clientError" | "serverError";
  userClass?:
    | "anonymous"
    | "owner"
    | "external"
    | "ownerAPIKey"
    | "externalAPIKey"
    | "ownerProcessing"
    | "externalProcessing";
  split?: ("day" | "refererApp" | "processing" | "resource")[];
}

export const aggQuerySchema = {
  "$id": "agg-query/schema.json",
  "title": "agg query",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "start",
    "end"
  ],
  "properties": {
    "start": {
      "type": "string",
      "format": "date"
    },
    "end": {
      "type": "string",
      "format": "date"
    },
    "operationTrack": {
      "$ref": "daily-api-metric/schema.json#/definitions/operationTrack"
    },
    "statusClass": {
      "$ref": "daily-api-metric/schema.json#/definitions/statusClass"
    },
    "userClass": {
      "$ref": "daily-api-metric/schema.json#/definitions/userClass"
    },
    "split": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "day",
          "refererApp",
          "processing",
          "resource"
        ]
      }
    }
  }
}
