/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface AggQuery {
    start: string;
    end: string;
    operationTrack?: "readDataFiles" | "readDataAPI" | "openApplication";
    statusClass?: "info" | "ok" | "redirect" | "clientError" | "serverError";
    userClass?: "anonymous" | "owner" | "external" | "ownerAPIKey" | "externalAPIKey" | "ownerProcessing" | "externalProcessing";
    split?: ("day" | "refererApp" | "processing" | "resource")[];
}
export declare const aggQuerySchema: {
    $id: string;
    title: string;
    type: string;
    additionalProperties: boolean;
    required: string[];
    properties: {
        start: {
            type: string;
            format: string;
        };
        end: {
            type: string;
            format: string;
        };
        operationTrack: {
            $ref: string;
        };
        statusClass: {
            $ref: string;
        };
        userClass: {
            $ref: string;
        };
        split: {
            type: string;
            items: {
                type: string;
                enum: string[];
            };
        };
    };
};
