// Code generated by jtd-codegen for TypeScript v0.2.1

export interface Config {
  directoryUrl: string;
  mongoUrl: string;
  port: number;
  publicUrl: string;
  get?: any;
  has?: any;
  util?: any;
}
