name: Build

on:
  workflow_call:

jobs:
  build-api:
    uses: ./.github/workflows/reuse-build-image.yml
    with:
      workspace: api

  build-daemon:
    uses: ./.github/workflows/reuse-build-image.yml
    with:
      workspace: daemon

  build-ui:
    uses: ./.github/workflows/reuse-build-image.yml
    with:
      workspace: ui